name: Deploy Node-React-Login-Template App (React + Node.js)

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.5.1
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Server
              env:
                  HOST: ${{ secrets.HOST_IP }}
                  USERNAME: ${{ secrets.USERNAME }}
                  TARGET_DIR: ${{ secrets.TARGET_DIR }}
              run: |
                  ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
                    export PATH=/root/.nvm/versions/node/v20.15.0/bin:$PATH #'which pm2' command on terminal will give the right path

                    cd $TARGET_DIR
                    git pull origin main

                    docker-compose down
                    docker-compose up -d --build

                  EOF
